### PR TITLE
DEV: update to 1.2.0a2

### LINKED ISSUE #57: feat: poetry v1.2
Hi all,

First, thank you for creating this feedstock! It's been very helpful.

Having the ability to install v1.2 would be helpful for my own projects. I'd like to inquire as to the possibility of building it, perhaps with a separate label or branch as described in https://github.com/conda-forge/poetry-feedstock/pull/56#issuecomment-994431613. Is this possible and what would it involve?

 I've never contributed to a cf feedstock before, but if needed, I might be able to offer some help.

### PR DESCRIPTION
**Pull request by xylar**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

closes #57

### CODE REVIEW

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
This won't work yet because the version of `cleo` needed isn't on the CDN yet, but I'm trying to get the pieces in place.

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Review by maresb — APPROVED** [review]

**Comment by xylar** [comment]
@maresb, thanks for the commits.

**Comment by xylar** [comment]
Some dependency seemingly hasn't been built for python 3.10.  I'll need to debug some more.

**Comment by maresb** [comment]
Ah, how did I miss that!? Good catch!

**Comment by xylar** [comment]
`virtualenv` in the range required here was not built for python 3.10.  I'm working on it.

**Comment by xylar** [comment]
Adding myself as a maintainer:
https://github.com/conda-forge/virtualenv-feedstock/pull/69
Then, I'll build the version I need (and get that feedstock back in better shape).

**Comment by xylar** [comment]
Almost there.  We just need to wait another 15 minutes or so for the new `virtualenv` builds with python 3.10 to be available via the CDN.

**Comment by xylar** [comment]
The CDN doesn't seem to be updating.  The packages are still not available.

**Pull request merged**
