### PR TITLE
Revert __unix virtual package

### PR DESCRIPTION
**Pull request by BastianZim**
This reverts commit 14d4a0851f80138a56e88b22a5e22ba5fcb1620c.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Follow up to https://github.com/conda-forge/poetry-feedstock/pull/99

### CODE REVIEW

**Comment by BastianZim** [comment]
@conda-forge-admin, please rerender

**Review by maresb — APPROVED** [review]
Thanks @BastianZim!

**Comment by maresb** [comment]
Shall we mark build 0 as broken? Otherwise it'll still be accessible to the solver as per https://github.com/conda-forge/poetry-feedstock/pull/99#issuecomment-2103120269

**Comment by BastianZim** [comment]
Yes! Done in https://github.com/conda-forge/admin-requests/pull/991 :)

**Comment by maresb** [comment]
Thanks so much @BastianZim!!!

**Pull request merged**
