### PR TITLE
1.2.0a2→1.2.0b1

### PR DESCRIPTION
**Pull request by maresb**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [X] Reset the build number to `0` (if the version changed)
* [X] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

Takes into account https://github.com/conda-forge/poetry-feedstock/issues/61

### CODE REVIEW

**Comment by maresb** [comment]
@conda-forge-admin, please rerender

**Comment by maresb** [comment]
Closing for the moment since this depends on poetry-core 1.1.0a7

**Comment by maresb** [comment]
Ooh, it seems that conda-forge/label/poetry_dev is not behind the CDN, so there's no waiting period! :smile:

**Comment by maresb** [comment]
@xylar ready for review

**Comment by maresb** [comment]
@conda-grayskull show requirements

**Comment by conda-grayskull** [comment]
Working on your request...

**Comment by xylar** [comment]
Looks good to me.  Should I merge?  I don't think `grayskull` is going to help...

**Comment by xylar** [comment]
Or you can merge when you're ready...

**Review by xylar — APPROVED** [review]

**Comment by maresb** [comment]
Thanks @xylar for taking a look!

**Pull request merged**
