### PR TITLE
[DEV] Bump to 1.2.0b2

### PR DESCRIPTION
**Pull request by maresb**
[Upstream diff](https://github.com/python-poetry/poetry/compare/1.2.0b1...1.2.0b2#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711)

Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [X] Reset the build number to `0` (if the version changed)
* [X] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by maresb** [comment]
@conda-forge-admin, please rerender

**Review by xylar — APPROVED** [review]
Looks right to me!  Thanks @maresb!

**Comment by xylar** [comment]
Hmm, it looks like `poetry-plugin-export` depends on `poetry`
https://github.com/conda-forge/poetry-plugin-export-feedstock/blob/main/recipe/meta.yaml#L21
and this version of `poetry` depends on `poetry-plugin-export`
https://github.com/conda-forge/poetry-feedstock/blob/0dc31c1def5e0481e9d82e5c3b4fa81a91ffa383/recipe/meta.yaml#L29
Such circular dependencies are allowed on pypi but not in conda packages.

The other problem is that I don't know how well it will work for a non-dev package (`poetry-plugin-export`) to require a dev package (this poetry).

**Comment by maresb** [comment]
Yes, this is the same circular dependency I was complaining about in #65.

What do you mean by a "non-dev" package? At least the label for `poetry-plugin-export` is `poetry_dev`.

Maybe I should complain upstream about the circular dependency.

**Comment by maresb** [comment]
It looks like the build is failing due to some missing packages.

**Comment by xylar** [comment]
I noticed after the fact that `poetry-plugin-export` was on `poetry_dev` so that's fine.  That's probably necessary for any package that has a dependency on a `*_dev` label.

**Comment by xylar** [comment]
Yes, the missing dependencies need to be built (or the recipes added) but the one that has me worried is:
```
package poetry-plugin-export-1.0.4-pyhc6ef2e2_0 requires poetry >=1.2.0b1dev0,<2.0.0, but none of the providers can be installed
```
I don't see any way to fix this unless `poetry-plugin-export` can be made to depend on `poetry-core` instead of `poetry`.  So, yes, I think you (we) probably need to complain upstream.

**Comment by maresb** [comment]
Hmm, good point. These circular dependencies are very confusing. Conda tries to set up an environment for building Poetry, installs `poetry-plugin-export` as a dependency, and then ends up installing Poetry itself as a subdependency. I don't know much about the implementation details of Conda, but this does indeed seem very bad.

**Comment by maresb** [comment]
WIP for missing platformdirs:
https://github.com/conda-forge/platformdirs-feedstock/pull/11

**Comment by maresb** [comment]
platformdirs is complete

**Comment by maresb** [comment]
The remaining dependencies seem to now be in order. The circular dependency is still problematic. Hopefully something will happen with https://github.com/python-poetry/poetry/pull/5980

**Comment by xylar** [comment]
closed via #71

**Pull request closed without merging**
