### PR TITLE
Add xylar as a maintainer

### PR DESCRIPTION
**Pull request by xylar**
Add/update URLs.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
I'm not bumping the build number for now. Let's see if it's necessary based on the rerender.

**Comment by xylar** [comment]
@maresb and @ocefpaf, my interest in joining this feedstock is that I would like to create a `dev` branch and build [1.2.0a2](https://github.com/python-poetry/poetry/releases/tag/1.2.0a2).  The [latest version for cattrs](https://github.com/conda-forge/cattrs-feedstock/pull/17) needs this version during setup.

**Comment by maresb** [comment]
Bumping build number is indeed unnecessary

**Comment by xylar** [comment]
Thanks @maresb!

**Comment by maresb** [comment]
Great to have you here!

**Pull request merged**
